# spring:
#    datasource:
#        driver-class-oracle:
#            jdbc:
#                driver:
#                    OracleDriver: ''
#        hikari:
#            connection-timeout: 60000
#            maximum-pool-size: 5
#        password: password
#        url: jdbc:oracle:thin:@localhost:1521:xe
#        username: system
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#    main:
#        banner-mode: 'off'

spring:
  datasource:

#   url: jdbc:oracle:thin:@localhost:1521/xe
#    username: springboot
#    password: springboot1
#    driver-class-name: oracle.jdbc.OracleDriver
 # platform: mysql
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /console  
endpoints:
  sensitive: false
  enabled: true
  mappings:
    enabled: true
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762
#spring:
#  application:
#    name: service