drop table if exists `ORDERS`;
CREATE TABLE `ORDERS` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ORDERID` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `CREATED_DATE` DATE,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
