spring:
  datasource:
    url: jdbc:h2:mem:testdb3;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
#    initialize: true
    schema: schema-h2.sql
    
  h2:
    console:
      enabled: true
      path: /console  
