CREATE SCHEMA IF NOT EXISTS  "PUBLIC"; 
DROP TABLE IF EXISTS "PUBLIC"."FRUIT";
CREATE TABLE "PUBLIC"."FRUIT" (
  "ID" INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  "NAME" VARCHAR(100) NOT NULL,
  "UNITPRICE" INT NOT NULL,
  PRIMARY KEY (`ID`)
) ;
INSERT INTO FRUIT (ID,NAME, UNITPRICE) VALUES
  (1,'apple', 1),
  (2,'orange', 2),
  (3,'banana', 3);
