CREATE SCHEMA IF NOT EXISTS  "PUBLIC"; 
DROP TABLE IF EXISTS "PUBLIC"."FRUIT";
CREATE TABLE "PUBLIC"."FRUIT" (
  "ID" INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  "NAME" VARCHAR(100) NOT NULL,
  "UNITPRICE" INT NOT NULL,
  "DESCRIP" VARCHAR(100),
  PRIMARY KEY (`ID`)
) ;

