drop table if exists `CUSTOMER`;
CREATE TABLE `CUSTOMER` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `AGE` INT NOT NULL,
  `PHONE` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(100) NOT NULL,
  `CREATED_DATE` DATE,
  PRIMARY KEY (`ID`)
) ;
